apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-service"
  labels:
    {{- include "deployment-svc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "deployment-svc.selectorLabels" . | nindent 4 }}
